spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XipKlkEc8VLlKgM59OC01yV9WC2y7t7TISTVBYLuQG3CGPz/ph3dSwxtNMxjhJ548592hcelCVmuzEuRJJPP2dS6//yQrpBdBbujHL4m9c4=)
    username: ENC(n1+fm+uUm/VLP6b0uTsVjeHAkMIobcWsdcfMqW+d8lvMUJKMH/jv9Se7C9hY6pG1)
    password: ENC(wjhc+VfBjNy+DbgceiG+2/4CPBkLFiDaGqSjjyMRaThj/XtXkWNgPQSQuN4FO0Ge)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true